<a href="https://colab.research.google.com/github/Dilanveliz/DilanIA/blob/main/Leccion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!python --version
import numpy as np


Python 3.10.12


In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
vector = np.random.rand(10)
max_index = np.argmax(vector)
vector[max_index] = 0
print("Vector original:")
print(vector)

Vector original:
[0.24218706 0.8733655  0.44249251 0.         0.02602823 0.07756089
 0.57919123 0.59942616 0.23855191 0.4322758 ]


In [7]:
arr = np.array([1, 8, 3, 8, 5, 6, 8, 2, 8, 0])
for num in arr:
    if num == 8:
        print(num)

8
8
8
8


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
numbers_to_print = [3, 4, 5]
for num in numbers_to_print:
    if num in arr:
        print(num)


3
4
5


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
ultimos_cuatro = arr[-4:]
print("Los últimos 4 números del arreglo son:", ultimos_cuatro)

Los últimos 4 números del arreglo son: [4 5 6 7]


In [10]:
matrix = np.ones((3, 3)).astype(bool)
print(matrix)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odd_numbers = arr[arr % 2 != 0]
print("Odd numbers in the array:", odd_numbers)

Odd numbers in the array: [1 3 5 7 9]


In [12]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
vector = np.array([1, 2, 3, 4, 5])
vector_revertido = vector[::-1]
print("Vector original:", vector)
print("Vector revertido:", vector_revertido)

Vector original: [1 2 3 4 5]
Vector revertido: [5 4 3 2 1]


In [14]:
matriz = np.random.randint(0, 100, size=(10, 10))
minimo_valor = np.min(matriz)
maximo_valor = np.max(matriz)
print(matriz)
print("\nValor mínimo en la matriz:", minimo_valor)
print("Valor máximo en la matriz:", maximo_valor)

[[56 66 91 10 88 83 13 76  8 35]
 [ 5 37 98 33 57 79 47 99 52 48]
 [65 77  7 83  6 75 64 97 51 48]
 [49 42 38 31 15 67 20 85 44 49]
 [52 12 53 81 60 49 37 52 84 51]
 [52 42 68 47 42 44 81 23  1 17]
 [60 67 68 27 43 64 61 18  4 59]
 [25 34 72 59 42 25 35 85 43 28]
 [ 0 34  3 72 52 29 69 65 57 65]
 [31 45  3 19 79 93 22  5 41 21]]

Valor mínimo en la matriz: 0
Valor máximo en la matriz: 99


In [15]:
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.10530222 0.58797819 0.07796341]
  [0.91235913 0.61810894 0.09461441]
  [0.95827033 0.69310105 0.86818691]]

 [[0.05390677 0.96528804 0.64089579]
  [0.03286782 0.71556188 0.11366595]
  [0.58850398 0.92440905 0.92305344]]

 [[0.35012912 0.31226198 0.82406482]
  [0.89174305 0.96362772 0.86024693]
  [0.27321663 0.12392633 0.71224868]]]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices_impares = arr % 2 != 0
arr[indices_impares] = -1
print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [17]:
arr_float = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr_float)
print("Tipo de datos:", arr_float.dtype)

[1. 2. 3. 4. 5.]
Tipo de datos: float64


In [18]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_2d = arr_1d.reshape(2, -1)
print("Arreglo original (1D):")
print(arr_1d)
print("\nArreglo convertido a 2D (2 filas):")
print(arr_2d)

Arreglo original (1D):
[1 2 3 4 5 6 7 8]

Arreglo convertido a 2D (2 filas):
[[1 2 3 4]
 [5 6 7 8]]


In [19]:
z1 = np.random.randint(0, 10, 10)
z2 = np.random.randint(0, 10, 10)
common_values = np.intersect1d(z1, z2)
print("Valores comunes entre z1 y z2:")
print(common_values)

Valores comunes entre z1 y z2:
[2 4 5 9]


In [20]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 8, 5)
son_iguales = np.array_equal(A, B)
if son_iguales:
    print("Los arreglos A y B son iguales.")
else:
    print("Los arreglos A y B no son iguales.")

Los arreglos A y B no son iguales.


In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_array = np.vstack((a, b))
print("Arreglo apilado verticalmente:")
print(stacked_array)

Arreglo apilado verticalmente:
[[1 2 3]
 [4 5 6]]


In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_array = np.hstack((a, b))
print("Arreglo apilado horizontalmente:")
print(stacked_array)

Arreglo apilado horizontalmente:
[1 2 3 4 5 6]


In [23]:
tmp = np.array([2, 6, 9, 12, 3, 8, 4, 7, 10])
resultado = tmp[(tmp >= 5) & (tmp <= 10)]

# Imprimir el resultado
print("Elementos entre 5 y 10 del arreglo tmp:")
print(resultado)

Elementos entre 5 y 10 del arreglo tmp:
[ 6  9  8  7 10]


In [32]:
def funcion_escalar_o_arreglo(x):
  if np.isscalar(x):
        x = np.array(x)
        resultado = np.square(x)

        return resultado
valor_escalar = 5
valores_arreglo = np.array([1, 2, 3, 4, 5])
resultado_escalar = funcion_escalar_o_arreglo(valor_escalar)
print("Resultado para valor escalar:", resultado_escalar)
resultado_arreglo = funcion_escalar_o_arreglo(valores_arreglo)
print("Resultado para arreglo:", resultado_arreglo)

Resultado para valor escalar: 25
Resultado para arreglo: None


In [33]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr[:, [1, 2]] = arr[:, [2, 1]]

# Imprimir la matriz resultante
print("Matriz con columnas 1 y 2 intercambiadas:")
print(arr)

Matriz con columnas 1 y 2 intercambiadas:
[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [34]:
# Crear un arreglo bidimensional de 5x3 con números enteros aleatorios entre 5 y 10
arr = np.random.randint(5, 11, size=(5, 3))

# Imprimir la matriz creada
print("Matriz de números enteros aleatorios entre 5 y 10:")
print(arr)

Matriz de números enteros aleatorios entre 5 y 10:
[[10  9  7]
 [ 9  6  6]
 [ 7  8  8]
 [10 10  7]
 [ 9  5  7]]
