<a href="https://colab.research.google.com/github/Dilanveliz/DilanIA/blob/main/semana13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as algebraLineal


a=algebraLineal.array([11,22,33])
print(a.shape)
print(type(a))
print(a)

print(a[1])
print(a[:2])
print(a[1:])

a[2] = 800

print("Arreglo actualizado:", a)

(3,)
<class 'numpy.ndarray'>
[11 22 33]
22
[11 22]
[22 33]
Arreglo actualizado: [ 11  22 800]


In [ ]:
import numpy as np
b=np.array([[1,2,3],[11,22,33],[111,222,333]])
print(b.shape)
print(type(b))
print(b)
print(b[1,1])
print('BEFORE')
aux=b[1:,1:]
print(aux.shape)
print(aux)
print('AFTER')
b[2, 2] = 1000
print(b)



(3, 3)
<class 'numpy.ndarray'>
[[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
22
BEFORE
(2, 2)
[[ 22  33]
 [222 333]]
AFTER
[[   1    2    3]
 [  11   22   33]
 [ 111  222 1000]]


In [ ]:
c=np.zeros([4,4])
print(c)
print(c.shape)
d=np.full([4,4],5)
print(d)
print(d.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
(4, 4)


In [ ]:
e=np.eye(3,3)
print(e)
f=np.ones((4,5))

print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
g=np.random.random((5,5))
print(g)

[[0.44380197 0.83845146 0.6348503  0.79082498 0.56083616]
 [0.9305694  0.74204612 0.72289164 0.22853079 0.62732653]
 [0.59332798 0.80150479 0.37641618 0.74021569 0.91187627]
 [0.97459179 0.90089556 0.58961864 0.99735617 0.93862634]
 [0.25723303 0.12087898 0.0207434  0.85967577 0.89669099]]


In [ ]:
tmp1=np.random.randint(1,20,(4,3))
print(tmp1)
rows=np.array([0,1,2,0])
cols=np.arange(4)
print(rows)
print(cols)



[[ 5 16  8]
 [15  7 11]
 [ 1 16  4]
 [ 8 18 16]]
[0 1 2 0]
[0 1 2 3]


IndexError: index 3 is out of bounds for axis 1 with size 3

In [33]:
f[row,cols]=100
print(f)

[[100.   1.   1.   1.   1.]
 [  1. 100.   1.   1.   1.]
 [  1.   1. 100.   1.   1.]
 [  1.   1.   1. 100.   1.]]


In [36]:
tmp1=np.random.randint(20,50,(6,6))
print(tmp1)

[[36 47 47 46 46 20]
 [25 25 41 36 47 49]
 [34 35 43 24 28 40]
 [34 30 25 45 35 38]
 [20 20 32 43 42 45]
 [45 39 49 34 31 29]]


In [37]:
filter=[tmp1>45]
print(filter)

[array([[False,  True,  True,  True,  True, False],
       [False, False, False, False,  True,  True],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False,  True, False, False, False]])]


In [39]:
filter = tmp1 > 45  # Create a boolean mask directly
print(filter)
print(tmp1[filter])

[[False  True  True  True  True False]
 [False False False False  True  True]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False  True False False False]]
[47 47 46 46 47 49 49]


In [40]:
tmp1=np.random.randint(1,100,(10,10))
print(tmp1)

[[46 62 26 40 71 32 55 68 27 83]
 [19 86 83 91 62 83  2 34 89 21]
 [60 52 91 22 72 38 97 59 19 53]
 [98 79 53  4  2 41 27 11 57 40]
 [ 9  8 40 50 41 41 97 78 31 88]
 [10 36 36 75 48 47 34 90 66 73]
 [29 66 25 77 68 98  7 94 68  2]
 [67 14 66 77 24 55 78 84 86  3]
 [24 75 80 91 62 79  4 45 66 54]
 [92 90 45 20 19 51 58 60  3 99]]


In [41]:
filter=(tmp1%2==0)
print(filter)
print(tmp1[filter])

[[ True  True  True  True False  True False  True False False]
 [False  True False False  True False  True  True False False]
 [ True  True False  True  True  True False False False False]
 [ True False False  True  True False False False False  True]
 [False  True  True  True False False False  True False  True]
 [ True  True  True False  True False  True  True  True False]
 [False  True False False  True  True False  True  True  True]
 [False  True  True False  True False  True  True  True False]
 [ True False  True False  True False  True False  True  True]
 [ True  True False  True False False  True  True False False]]
[46 62 26 40 32 68 86 62  2 34 60 52 22 72 38 98  4  2 40  8 40 50 78 88
 10 36 36 48 34 90 66 66 68 98 94 68  2 14 66 24 78 84 86 24 80 62  4 66
 54 92 90 20 58 60]


In [42]:
tmp3=np.array([1,2,3,4,5],dtype=np.float64)
print(tmp3.dtype)

float64


In [43]:
# prompt: crear una matriz con dos dimensiones

import numpy as np

# Create a 2D array with shape (3, 4)
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Print the matrix
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [52]:
x=np.array([[1,2],[11,22]])
y=np.array([[22,33],[44,55]])
print(x)
print(y)

print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.sqrt(x))

[[ 1  2]
 [11 22]]
[[22 33]
 [44 55]]
[[23 35]
 [55 77]]
[[-21 -31]
 [-33 -33]]
[[  22   66]
 [ 484 1210]]
[[0.04545455 0.06060606]
 [0.25       0.4       ]]
[[1.         1.41421356]
 [3.31662479 4.69041576]]


In [53]:
tmp1=np.random.randint(1,10,(2,5))
print(tmp1)
aux=tmp1.mean()
print(aux)

[[7 1 8 1 5]
 [6 3 3 8 3]]
4.5


In [54]:
print(tmp1.sum(axis=0))
print(tmp1.sum(axis=1))

[13  4 11  9  8]
[22 23]
